behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 1e-4
      beta: 1e-4
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 5
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.93
        strength: 1.0
      gail:
        gamma: 0.8
        strength: 0.2
        demo_path: Demos
        network_settings:
          normalize: true
    init_path: null
    keep_checkpoints: 10
    max_steps: 5e6
    time_horizon: 256
    summary_freq: 50000
    threaded: true
    self_play: null
    behavioral_cloning:
       strength: 0.15
       demo_path: Demos
       